// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMngciDwPVWKV6o2x3Sr70nFkZLynlE9E',
    appId: '1:195491358084:web:1bc995bee35672698229d1',
    messagingSenderId: '195491358084',
    projectId: 'personal-gallery-72e88',
    authDomain: 'personal-gallery-72e88.firebaseapp.com',
    storageBucket: 'personal-gallery-72e88.firebasestorage.app',
    measurementId: 'G-TZ55KF5K13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmaqkqgP0QsE_qBhdaKMqJIeJSUIr78Fs',
    appId: '1:195491358084:android:e4a2ea824cfbfce48229d1',
    messagingSenderId: '195491358084',
    projectId: 'personal-gallery-72e88',
    storageBucket: 'personal-gallery-72e88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8_w-l7j5EXG_k6jGNLak5bq3v2qNMXkk',
    appId: '1:195491358084:ios:28d1d10ef6e787208229d1',
    messagingSenderId: '195491358084',
    projectId: 'personal-gallery-72e88',
    storageBucket: 'personal-gallery-72e88.firebasestorage.app',
    iosBundleId: 'com.example.personalGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8_w-l7j5EXG_k6jGNLak5bq3v2qNMXkk',
    appId: '1:195491358084:ios:28d1d10ef6e787208229d1',
    messagingSenderId: '195491358084',
    projectId: 'personal-gallery-72e88',
    storageBucket: 'personal-gallery-72e88.firebasestorage.app',
    iosBundleId: 'com.example.personalGallery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMngciDwPVWKV6o2x3Sr70nFkZLynlE9E',
    appId: '1:195491358084:web:19d736647bf06a788229d1',
    messagingSenderId: '195491358084',
    projectId: 'personal-gallery-72e88',
    authDomain: 'personal-gallery-72e88.firebaseapp.com',
    storageBucket: 'personal-gallery-72e88.firebasestorage.app',
    measurementId: 'G-CBW8FJ1EBN',
  );

}